/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/WebSocketClient`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AddScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AdminScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AnalyticsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ClientScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ReaderScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/StudentScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/UpdateScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/WebSocketClient`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AddScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AdminScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AnalyticsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ClientScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/DetailsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ListScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ReaderScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/StudentScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/UpdateScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/WebSocketClient${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/AddScreen${`?${string}` | `#${string}` | ''}` | `/screens/AdminScreen${`?${string}` | `#${string}` | ''}` | `/screens/AnalyticsScreen${`?${string}` | `#${string}` | ''}` | `/screens/ClientScreen${`?${string}` | `#${string}` | ''}` | `/screens/DetailsScreen${`?${string}` | `#${string}` | ''}` | `/screens/ListScreen${`?${string}` | `#${string}` | ''}` | `/screens/ReaderScreen${`?${string}` | `#${string}` | ''}` | `/screens/StudentScreen${`?${string}` | `#${string}` | ''}` | `/screens/UpdateScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/WebSocketClient`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AddScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AdminScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AnalyticsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ClientScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ReaderScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/StudentScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/UpdateScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
